# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Batos Jugando
email: hola@batosjugando.com
description: >- # this means to ignore newlines until "baseurl:"
  Somos un grupo de gente que juega videojuegos, transmite sus
  partidas y comenta cosas en el podcast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://batosjugando.com" # the base hostname & protocol for your site, e.g. http://example.com
twitch: https://www.twitch.tv/batosjugando
podcast: /podcast

menu:
  - title: Home
    url: /
  - title: Podcast
    url: /podcast
  - title: Discord
    url: http://discord.batosjugando.com
    external: true
  - title: Twitch
    url: https://www.twitch.tv/batosjugando
    external: true
  - title: Twitter
    url: https://twitter.com/batosjugando
    external: true
  - title: Youtube
    url: https://www.youtube.com/channel/UCU40Vk0baBrI998m5aGyZ2w
    external: true
  - title: Crew
    url: /crew

# Fill later (new page) 
others:
  - title: Gran Pregunta
    description: 'Simplemente preguntas random para iniciar un buen dia.'
    url: 'http://granpregunta.com'
  - title: Frases del Erick
    description: 'Hay un dude que dice MUCHAS cosas y cuando lo escucha alguna persona, tuitea sus frases.'
    url: 'https://frasesdelerick.com'

crew:
  - title: El oso (jmsalcido)
    url: https://twitter.com/jmsalcido
  - title: Pozolito (tony)
    url: https://twitter.com/_tonymtz
  - title: TheMuppet
    url:
  - title: Gallo Negro (Carlos The Human)
    url: https://twitter.com/CarlosTheHuman

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
